### ISSUE TITLE
Add your name to contributors.md file

### ISSUE THREAD

**Issue by agdhruv** [ashoka-cs/people#1]
This is a very simple issue that will get you started.
This is basically what you have to do: **send a pull request (PR)** to this repository.
To get a step by step guide on how to do it, go to this link: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github. Once we have enough contributors, we will start working on a legit project.

Also, before you send any pull request, make sure you register to Hacktoberfest at https://hacktoberfest.digitalocean.com.

**Comment by aldocano** [comment]
#6
