### ISSUE TITLE
Configure Travis CI build system to work with repository

### ISSUE THREAD

**Issue by mayukhnair** [ashoka-cs/people#20]
The .travis.yml file is still improperly configured for this repository. It has to be configured for program builds in Python. Dependencies will be added later when defined in `readme.md`.

To test whether your fixes work, first set up an account at http://travis-ci.org and see that your fork of this repository is showing up. Once you make changes and save to your fork, Travis CI will automatically start building. If it passes, the configuration is successful.

Once confirmed, create a pull request and we'll merge it in.

**Comment by ayushkalani** [comment]
I'm interested in doing this. @mayukhnair

**Comment by mayukhnair** [comment]
@ayushkalani Go ahead

**Comment by mayukhnair** [comment]
Issue resolved with #34 courtesy @ayushkalani.
